# Generated by Django 5.1.3 on 2024-11-14 19:04

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appHouseTasker', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='is_overlapping',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='task',
            name='duration',
            field=models.DurationField(),
        ),
        migrations.AlterField(
            model_name='task',
            name='start_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
