# Generated by Django 5.1.2 on 2024-11-09 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appHouseTasker', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Resource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Nombre del recurso, e.g., Jabon, Coche, Llaves.', max_length=100, unique=True)),
                ('description', models.TextField(blank=True, help_text='Descripción opcional del recurso y sus características.')),
                ('quantity', models.PositiveIntegerField(default=1, help_text='Cantidad disponible de este recurso.')),
                ('category', models.CharField(choices=[('cleaning', 'Limpieza'), ('vehicle', 'Vehículo'), ('kitchen', 'Cocina'), ('others', 'Otros')], default='others', help_text='Categoría del recurso.', max_length=50)),
                ('is_available', models.BooleanField(default=True, help_text='Indica si el recurso está disponible para uso.')),
            ],
        ),
    ]
