# Generated by Django 5.1.2 on 2024-11-12 14:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appHouseTasker', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='role',
        ),
    ]
